### ISSUE TITLE
Observations are -1 for defender after reset.

### ISSUE THREAD

**Issue by kasanari** [mal-lang/mal-petting-zoo-simulator#6]

**Comment by andrewbwm** [comment]
Same solution as for #11 

Fixed in 094d4a1794d174e56aef3cf98067eedf891dc48b.

The reset method now goes through the same function to generate observations, rewards, terminations, truncantions, and infos. Even though it is only expected to make use of observations and infos. However, if a non-viable episode is given it will immediately terminate it, but that might be the desired behaviour anyway.
